# Generated by Django 4.2.7 on 2025-09-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the category'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='E.g., cotton, silk, wood', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, help_text='E.g., Banaras, Kanjivaram', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
